name: DAPpyr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - jupyterlab
  - matplotlib
  - pandas
  - numpy
  - scipy
  - numba
  - xarray
  - requests
  - pyyaml
  - conda-forge::numbalsoda